"use strict";
var message = ("Hey Zaid,I have started Learning TYPESCRIPT");
console.log(message);
var myName = ("My Name is Muhammad Zaid");
console.log(myName);
var num1 = 1;
var num2 = 2;
var num3 = 3;
var num4 = 4;
var num5 = 5;
var num6 = 6;
var num7 = 7;
var num8 = 8;
var num9 = 9;
var num10 = 10;
var sum = num1 + num2 + num3 + num4 + num5 + num6 + num7 + num8 + num9 + num10;
console.log(sum);
var subtract = num1 - num2 - num3 - num4 - num5 - num6 - num7 - num8 - num9 - num10;
console.log(subtract);
var multiply = num1 * num2 * num3 * num4 * num5 * num6 * num7 * num8 * num9 * num10;
console.log(multiply);
var divide = num5 / num9;
console.log(divide);
